# Create new comment for the post
POST http://localhost:3001/api/posts/e653f55d-bd5c-4a8d-8f32-ebabbb0d3b98/comments HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NDI4NThlMjQ0YTI5MTc0ODEzNmExNCIsImVtYWlsIjoidGVzdC11c2VyNTdAbWFpbC5ydSIsIm5hbWUiOiJUZXN0VXNlciIsImlhdCI6MTcxNTYzNjQ3MCwiZXhwIjoxNzE1NzIyODcwfQ.aQaOlTCIDoEUybFnVCtVbTO3J5Xw4JnWzFv_gyTCis4
Content-Type: application/json

{
  "message": "Test post comment message..."
}

###

# Delete comment by id
DELETE http://localhost:3001/api/posts/e653f55d-bd5c-4a8d-8f32-ebabbb0d3b98/comments/0ff7b2f4-7d69-40b7-aaf9-8576143fad96 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NDI4NThlMjQ0YTI5MTc0ODEzNmExNCIsImVtYWlsIjoidGVzdC11c2VyNTdAbWFpbC5ydSIsIm5hbWUiOiJUZXN0VXNlciIsImlhdCI6MTcxNTYzNjQ3MCwiZXhwIjoxNzE1NzIyODcwfQ.aQaOlTCIDoEUybFnVCtVbTO3J5Xw4JnWzFv_gyTCis4

###

# Get comments list by a post id
GET http://localhost:3001/api/posts/e653f55d-bd5c-4a8d-8f32-ebabbb0d3b98/comments/find HTTP/1.1

###

# Get comment by id
GET http://localhost:3001/api/posts/e653f55d-bd5c-4a8d-8f32-ebabbb0d3b98/comments/0ff7b2f4-7d69-40b7-aaf9-8576143fad96 HTTP/1.1
